// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbN43HHnOFTWHthw0NLeIRWjwwosof5rg',
    appId: '1:305899872534:web:60a33f470f109a3b10b037',
    messagingSenderId: '305899872534',
    projectId: 'fir-auth-3832b',
    authDomain: 'fir-auth-3832b.firebaseapp.com',
    storageBucket: 'fir-auth-3832b.appspot.com',
    measurementId: 'G-ELBKCENLP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqQb4PV_fGWdjnSBvdD4MCuQ90O-JVvcA',
    appId: '1:305899872534:android:619fcffc4fe965d410b037',
    messagingSenderId: '305899872534',
    projectId: 'fir-auth-3832b',
    storageBucket: 'fir-auth-3832b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNIPWu13s6yO1nvW0OMbb_63AquHm2qVw',
    appId: '1:305899872534:ios:4309d818502ab28310b037',
    messagingSenderId: '305899872534',
    projectId: 'fir-auth-3832b',
    storageBucket: 'fir-auth-3832b.appspot.com',
    androidClientId: '305899872534-1tul7c7an3n8c5164ph3thtmunruba79.apps.googleusercontent.com',
    iosClientId: '305899872534-0nonj3v1vrjog2idfi5ne85jg5ukru28.apps.googleusercontent.com',
    iosBundleId: 'com.example.dozerOwner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNIPWu13s6yO1nvW0OMbb_63AquHm2qVw',
    appId: '1:305899872534:ios:059aa392e04683f210b037',
    messagingSenderId: '305899872534',
    projectId: 'fir-auth-3832b',
    storageBucket: 'fir-auth-3832b.appspot.com',
    androidClientId: '305899872534-1tul7c7an3n8c5164ph3thtmunruba79.apps.googleusercontent.com',
    iosClientId: '305899872534-kiashosv01i0kh8pf0oauifageku84g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dozerOwner.RunnerTests',
  );
}
